#!/bin/python3

import math
import os
import random
import re
import sys

from collections import Counter

if __name__ == '__main__':
    s = sorted(input())

c=Counter(s).most_common(3)  #counter returns distinct key and count of the keys (values) in dictionary form  
for i in c:
    print(*i)

